/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 0feabb7ba0d4558ee99d0b88995d8737)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	NEXTAUTH_URL: string;
	NEXTAUTH_SECRET: string;
	AI_PROVIDER: string;
	OPENAI_API_KEY: string;
	OPENAI_MODEL: string;
	NEXT_PUBLIC_KOKORO_MODEL_ID: string;
	NEXT_PUBLIC_KOKORO_DEFAULT_VOICE: string;
	NEXT_PUBLIC_VIENEU_DEFAULT_VOICE: string;
	VIENEU_URL: string;
	TTS_API_KEY: string;
	TTS_CACHE_DIR: string;
	KOKORO_MODEL_ID: string;
	KOKORO_DEFAULT_VOICE: string;
	VIENEU_DEFAULT_VOICE: string;
	LOG_LEVEL: string;
	WORKER_SELF_REFERENCE: Fetcher /* listena-english */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "NEXTAUTH_URL" | "NEXTAUTH_SECRET" | "AI_PROVIDER" | "OPENAI_API_KEY" | "OPENAI_MODEL" | "NEXT_PUBLIC_KOKORO_MODEL_ID" | "NEXT_PUBLIC_KOKORO_DEFAULT_VOICE" | "NEXT_PUBLIC_VIENEU_DEFAULT_VOICE" | "VIENEU_URL" | "TTS_API_KEY" | "TTS_CACHE_DIR" | "KOKORO_MODEL_ID" | "KOKORO_DEFAULT_VOICE" | "VIENEU_DEFAULT_VOICE" | "LOG_LEVEL">> {}
}
