/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --env-interface=CloudflareEnv` (hash: 111c0a09f15fe8af722413ee9cdb53d4)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH_URL: "https://listena-english.tuanank2112.workers.dev";
	DATABASE_URL: string;
	NEXTAUTH_URL: string;
	NEXTAUTH_SECRET: string;
	AI_PROVIDER: string;
	KIRAAI_API_KEY: string;
	KIRAAI_MODEL: string;
	KIRAAI_BASE_URL: string;
	OPENAI_API_KEY: string;
	OPENAI_MODEL: string;
	OPENAI_BASE_URL: string;
	NEXT_PUBLIC_KOKORO_MODEL_ID: string;
	NEXT_PUBLIC_KOKORO_DEFAULT_VOICE: string;
	VIENEU_URL: string;
	TTS_API_KEY: string;
	TTS_PROXY_CACHE_DIR: string;
	TTS_CACHE_DIR: string;
	KOKORO_MODEL_ID: string;
	KOKORO_DEFAULT_VOICE: string;
	VIENEU_DEFAULT_VOICE: string;
	LOG_LEVEL: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_URL" | "DATABASE_URL" | "NEXTAUTH_URL" | "NEXTAUTH_SECRET" | "AI_PROVIDER" | "KIRAAI_API_KEY" | "KIRAAI_MODEL" | "KIRAAI_BASE_URL" | "OPENAI_API_KEY" | "OPENAI_MODEL" | "OPENAI_BASE_URL" | "NEXT_PUBLIC_KOKORO_MODEL_ID" | "NEXT_PUBLIC_KOKORO_DEFAULT_VOICE" | "VIENEU_URL" | "TTS_API_KEY" | "TTS_PROXY_CACHE_DIR" | "TTS_CACHE_DIR" | "KOKORO_MODEL_ID" | "KOKORO_DEFAULT_VOICE" | "VIENEU_DEFAULT_VOICE" | "LOG_LEVEL">> {}
}
