"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import { ArrowRight, Sparkles } from "lucide-react";

export default function RegisterPage() {
  const router = useRouter();
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState<"LEARNER"|"TEACHER">("LEARNER"); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");const response=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password,role})});if(!response.ok){const payload=await response.json();setError(payload.error||"Chưa tạo được tài khoản.");setLoading(false);return;}const result=await signIn("credentials",{email,password,redirect:false});if(result?.ok){router.push(role==="TEACHER"?"/teacher/dashboard":"/learner/dashboard");router.refresh();}}
  return <main className="flex min-h-screen items-center justify-center px-4 py-8"><div className="w-full max-w-lg"><Link href="/" className="mb-8 inline-flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#176b55] text-white"><Sparkles className="h-5 w-5" /></span><span className="font-black">ListenAI</span></Link><div className="paper-card rounded-[32px] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ef765d]">Join the studio</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em]">Tạo tài khoản.</h1><form onSubmit={submit} className="mt-7 space-y-4">{[["Họ tên",name,setName,"Nguyễn Văn A","text"],["Email",email,setEmail,"you@example.com","email"],["Mật khẩu",password,setPassword,"Tối thiểu 6 ký tự","password"]].map(([label,value,setter,placeholder,type])=><label key={label as string} className="block text-sm font-black">{label as string}<input type={type as string} value={value as string} onChange={event=>(setter as React.Dispatch<React.SetStateAction<string>>)(event.target.value)} required minLength={type==="password"?6:undefined} placeholder={placeholder as string} className="mt-2 min-h-13 w-full rounded-2xl border-2 border-[#ded8cc] bg-white px-4 font-bold outline-none focus:border-[#176b55]" /></label>)}<div><p className="text-sm font-black">Bạn là</p><div className="mt-2 grid grid-cols-2 gap-2">{[["LEARNER","Học viên"],["TEACHER","Giáo viên"]].map(([value,label])=><button key={value} type="button" onClick={()=>setRole(value as "LEARNER"|"TEACHER")} className={`min-h-12 rounded-2xl text-sm font-black ${role===value?"bg-[#176b55] text-white":"bg-[#eee7da]"}`}>{label}</button>)}</div></div>{error&&<p role="alert" className="text-sm font-bold text-[#d6534d]">{error}</p>}<button disabled={loading} className="flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-[#18332d] text-sm font-black text-white disabled:opacity-50">{loading?"Đang tạo…":"Tạo tài khoản"}<ArrowRight className="h-4 w-4" /></button></form><p className="mt-5 text-center text-sm font-bold text-[#7b857f]">Đã có tài khoản? <Link href="/login" className="text-[#176b55]">Đăng nhập</Link></p></div></div></main>;
}
